# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Elements of Computing
author: <a href="https://americanstudies.nd.edu/faculty/katherine-walden/">Dr. Katherine Walden</a>
copyright: "2024"
logo: favicon.png
# Patterns to skip when building the book. Can be glob-style (e.g. "*skip.ipynb")
exclude_patterns: [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints", "**/in-progress", "**/other_files", "features", "scraps"]
# Auto-exclude files not in the toc
only_build_toc_files: false

#######################################################################################
# Execution settings
execute:
  execute_notebooks: cache  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
  #cache: ""    # A path to the jupyter cache that will be used to store execution artifacts. Defaults to `_build/.jupyter_cache/`
  #exclude_patterns: []    # A list of patterns to *skip* in execution (e.g. a notebook that takes a really long time)
  timeout: 30    # The maximum time (in seconds) each notebook cell is allowed to run.
  run_in_temp: false # If `True`, then a temporary directory will be created and used as the command working directory (cwd), otherwise the notebook's parent directory will be the cwd.
  allow_errors: true # If `False`, when a code cell raises an error the execution is stopped, otherwise all cells are always run.
  stderr_output: show  # One of 'show', 'remove', 'remove-warn', 'warn', 'error', 'severe'

#######################################################################################
# Parse and render settings
parse:
  myst_enable_extensions:  # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    # - amsmath
    - colon_fence
    # - deflist
    # - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    # - substitution
    - tasklist
  myst_url_schemes: [mailto, http, https] # URI schemes that will be recognised as external URLs in Markdown links
  myst_dmath_double_inline: true  # Allow display math ($$) within an inline context

#######################################################################################
# HTML-specific settings
html:
  favicon: "favicon.png"  # A path to a favicon image
  use_edit_page_button: false  # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button: true  # Whether to add a link to your repository button
  use_issues_button: false  # Whether to add an "open an issue" button
  use_multitoc_numbering: true   # Continuous numbering across parts/chapters
  extra_footer: |
    <div>
    <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img class="license" alt="Creative Commons License" src="https://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png" /></a> This book is licensed under a <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons BY-NC-SA 4.0 License</a>.
    </div>
  google_analytics_id: "G-JGEVHVC9DL"  # A GA id that can be used to track book views.
  home_page_in_navbar: false  # Whether to include your home page in the left Navigation Bar
  baseurl: "https://kwaldenphd/github.io/elements-of-computing"  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
  comments:
    hypothesis: false
    utterances: false

#######################################################################################
# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html

#######################################################################################
# Launch button settings
launch_buttons:
  notebook_interface: jupyterlab  # The interface interactive links will activate ["classic", "jupyterlab"]
  #binderhub_url: https://mybinder.org  # The URL of the BinderHub (e.g., https://mybinder.org)
#  jupyterhub_url            : ""  # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu)
#  thebe                     : False  # Add a thebe button to pages (requires the repository to run on Binder)
  colab_url: https://colab.research.google.com # The URL of Google Colab (e.g., https://colab.research.google.com)

# Information about where the book exists on the web
repository:
  url: https://github.com/kwaldenphd/elements-of-computing  # Online location of your book
  path_to_book: book  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: false
  use_repository_button: false
  
#######################################################################################
# Advanced and power-user settings
sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js